# Site settings
title: Adventures of a Libra & Gemini
email: cynthia.jq.wong@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cynthziawong.github.io/adventures-of-a-libra-and-gemini/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
